server:
  port: 8080

spring:
  application:
    name: diamond-shield-central

  datasource:
    url: jdbc:postgresql://localhost:5432/diamond_shield_central
    username: diamond
    password: diamond
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: "CHANGE_ME_TO_LONG_RANDOM_SECRET_64_BYTES_MINIMUM_FOR_PRODUCTION"
    access-token-ttl-minutes: 720

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.security: info